### ISSUE TITLE
FAMD code example not working

### ISSUE THREAD

**Issue by EsbenFThomas** [Cauchemare/Truncated_FAMD#1]
Running the exact same code as is shown in the FAMD example in the Project Description leads to an error:

Traceback (most recent call last):
  File "famd.py", line 10, in <module>
    famd.fit(X)
  File "/usr/local/lib/python3.7/site-packages/light_famd/famd.py", line 45, in fit
    return super().fit(X)
  File "/usr/local/lib/python3.7/site-packages/light_famd/mfa.py", line 70, in fit
    super().fit(self._build_X_global(X))  
  File "/usr/local/lib/python3.7/site-packages/light_famd/pca.py", line 68, in fit
    engine=self.engine
  File "/usr/local/lib/python3.7/site-packages/light_famd/svd.py", line 29, in compute_svd
    flip_sign=True
  File "/usr/local/lib/python3.7/site-packages/sklearn/utils/extmath.py", line 371, in randomized_svd
    Uhat, s, V = linalg.svd(B, full_matrices=False)
  File "/usr/local/lib/python3.7/site-packages/scipy/linalg/decomp_svd.py", line 109, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/usr/local/lib/python3.7/site-packages/scipy/_lib/_util.py", line 242, in _asarray_validated
    raise ValueError('object arrays are not supported')
ValueError: object arrays are not supported

**Comment by Cauchemare** [comment]
I have updated this package,you could update or directly remove-reinstall this package.
Good Luck!~
